<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="CptDatasetLoad" nsURI="http://com.misc.projects.cpt.datasetload"
    nsPrefix="cptload">
  <eClassifiers xsi:type="ecore:EClass" name="FPD" eSuperTypes="../../com.misc.common.moplaf.datasetload.ora.emf/model/datasetloadora.ecore#//DatasetLoadJdbcOraThin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="MasterData" eType="#//FPDMasterData"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SortingPlansSets" upperBound="-1"
        eType="#//FPDSortingPlansSet" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FPDTableGroup" eSuperTypes="../../com.misc.common.moplaf.datasetload.emf/model/datasetload.ecore#//TableGroup">
    <eStructuralFeatures xsi:type="ecore:EReference" name="FPD" eType="#//FPD" changeable="false"
        volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FPDMasterData" eSuperTypes="#//FPDTableGroup">
    <eStructuralFeatures xsi:type="ecore:EReference" name="SortingLevelTable" eType="#//SortingLevelsTable"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FPDSortingPlansSet" eSuperTypes="#//FPDTableGroup">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="FromDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ToDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SortingPlansTable" eType="#//SortingPlansTable"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SortingPlanOutputsTable"
        eType="#//SortingPlanOutputTable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SortingPlanInputsTable"
        eType="#//SortingPlanInputTable" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FPDSortingPanRow" eSuperTypes="../../com.misc.common.moplaf.datasetload.emf/model/datasetload.ecore#//TableRow">
    <eStructuralFeatures xsi:type="ecore:EReference" name="FPDSortingPlanTable" eType="#//FPDSortingPlanTable"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FPDSortingPlanTable" eSuperTypes="../../com.misc.common.moplaf.datasetload.emf/model/datasetload.ecore#//Table">
    <eStructuralFeatures xsi:type="ecore:EReference" name="FPDSortingPlansSet" eType="#//FPDSortingPlansSet"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MasterDataTable" eSuperTypes="../../com.misc.common.moplaf.datasetload.emf/model/datasetload.ecore#//Table"/>
  <eClassifiers xsi:type="ecore:EClass" name="SortingLevelsTable" eSuperTypes="#//MasterDataTable">
    <eOperations name="getRow" eType="#//SortingLevelRow">
      <eParameters name="sk" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SortinglevelRow" upperBound="-1"
        eType="#//SortingLevelRow" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SortingPlansTable" eSuperTypes="#//FPDSortingPlanTable">
    <eOperations name="getRow" eType="#//SortingPlanRow">
      <eParameters name="sk" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SortingPlansRow" upperBound="-1"
        eType="#//SortingPlanRow" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SortingPlanInputTable" eSuperTypes="#//FPDSortingPlanTable">
    <eOperations name="getRow" eType="#//SortingPlanOutputRow">
      <eParameters name="sortingPlanSk" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
      <eParameters name="sortingLevelSk" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
      <eParameters name="mechanizationLevelSk" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
      <eParameters name="throughputTypeSk" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SortingPlanInputRow" upperBound="-1"
        eType="#//SortingPlanInputRow" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SortingPlanOutputTable" eSuperTypes="#//FPDSortingPlanTable">
    <eOperations name="getRow" eType="#//SortingPlanOutputRow">
      <eParameters name="sortingPlanSk" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
      <eParameters name="sortingLevelSk" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
      <eParameters name="mechanizationLevelSk" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
      <eParameters name="throughputTypeSk" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
      <eParameters name="destination" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SortingPlanOutputRow" upperBound="-1"
        eType="#//SortingPlanOutputRow" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SortingLevelRow" eSuperTypes="../../com.misc.common.moplaf.datasetload.emf/model/datasetload.ecore#//TableRow">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SortingLevelSk" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SortingLevelName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SortingPlanRow" eSuperTypes="#//FPDSortingPanRow">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SortingPlanSk" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SortingPlanName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SortingLevelPLAGGSk" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Inputs" upperBound="-1"
        eType="#//SortingPlanInputRow" eOpposite="#//SortingPlanInputRow/SortingPlan"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Outputs" upperBound="-1"
        eType="#//SortingPlanOutputRow" eOpposite="#//SortingPlanOutputRow/SortingPlan"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SortingPlanOutputRow" eSuperTypes="#//FPDSortingPanRow">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SortingPlanSk" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SortingLevelAVCSSk" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="MechanizationLevelSk" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ThroughputTypeSk" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DestinationSk" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SortingPlan" eType="#//SortingPlanRow"
        eOpposite="#//SortingPlanRow/Outputs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SortingLevel" eType="#//SortingLevelRow"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SortingPlanInputRow" eSuperTypes="#//FPDSortingPanRow">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SortingPlanSk" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SortingLevelAVCSSk" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="MechanizationLevelSk" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ThroughputTypeSk" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SortingPlan" eType="#//SortingPlanRow"
        eOpposite="#//SortingPlanRow/Inputs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SortingLevel" eType="#//SortingLevelRow"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FPO" eSuperTypes="../../com.misc.common.moplaf.datasetload.ora.emf/model/datasetloadora.ecore#//DatasetLoadJdbcOraThin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ForecastUploads" upperBound="-1"
        eType="#//FPOForecastUpload" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FPOForecastUpload" eSuperTypes="../../com.misc.common.moplaf.datasetload.emf/model/datasetload.ecore#//TableGroup">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="FromDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ToDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Kind" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ForecastTable" lowerBound="1"
        eType="#//FPOForecastBuckets" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FPOForecastBucket" eSuperTypes="../../com.misc.common.moplaf.datasetload.emf/model/datasetload.ecore#//TableRow">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="BucketDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="BucketBeginTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="BucketEndTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="BucketHour" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Customer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="FirstSortingImc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="IntakeChannel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="IntakeLocation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DayPlus" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ThroughputType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="MechanizationLevel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SortingLevelAGG" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Volume" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="PublicationID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="TimeSeriesID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="BucketID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FPOForecastBuckets" eSuperTypes="../../com.misc.common.moplaf.datasetload.emf/model/datasetload.ecore#//Table">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ForecastRows" upperBound="-1"
        eType="#//FPOForecastBucket" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
